### ISSUE TITLE
Modify an issues pipeline

### ISSUE THREAD

**Issue by azenMatt** [ZenHubIO/API#24]
> I'd like to have this cover the ability to modify the position of zenhub issues via the API

ref: https://github.com/ZenHubIO/API/issues/10#issuecomment-226516903

**Comment by klinec** [comment]
This is a must have feature for continues deployment. I miss it so much

**Comment by azenMatt** [comment]
Hi @klinec - would you be able to provide a rough outline of your usecase for this? How would this help you with continuous deployment?

**Comment by gadelat** [comment]
@azenMatt I can answer that: Pipelines represent stages of the ticket. One of those in our case is testing by internal tester. When we merge the ticket, integration tests are run and if they pass, code is automatically deployed to the staging server. Now, here is the missing part: after the deployment, we currently have to move the ticket to testing pipeline manually. When ticket is in testing pipeline, tester knows that ticket is deployed to our staging server so he can start testing it.

Similar situation is when deploying to production server. When code is deployed to production, we have to move the tickets to LIVE pipeline manually.

**Comment by azenMatt** [comment]
Thank you for the thoughts @gadelat - that makes a lot of sense

We are starting to add some more end points into our API (starting with #19 ) this is a good candidate to add as a first write end point after that

**Comment by jfiore-ibm** [comment]
@azenMatt We also really could use this feature (We use ZenHub Enterprise).
For example, we are using some automation to reopen issues under certain conditions (breaks a build, another commit for that issue is merged, etc.)
When we reopen the issue, we would like to be able to move the pipeline back to "In Progress" instead of leaving it in its prior state (which was probably "QA Complete" if it was closed).

**Comment by andrewlow** [comment]
When this issue was originally opened, the title 'Modify position of an issue within a pipeline' more accurately reflected the use case I had in mind.

ZenHub maintains 2 'magic' bits of meta-data about an issue.
a) The pipeline
b) The order of the issue within that pipeline

I care about (b)  -- but agree that (a) would also be useful to be able to modify.

The current API allows you to query ZenHub to get both back. The pipeline and order within the pipeline are available to be read.

The request is that the API allow write back of changes to the pipeline AND order within the pipeline of a given issue.

**Comment by peterjwest** [comment]
This would be really useful for my team. The only part we need is to be able to move one issue from one pipeline to another, but moving issues within a pipeline would be nice too.

**Comment by chance-focalcast** [comment]
Our company would also benefit from this. There are various aspects of our QA/deployment process that could be easily automated. It was a little disappointing when I realized there were no PUT/POST endpoints setup to move issues between pipelines.

**Comment by azenMatt** [comment]
We just put a number of new API endpoints live, including Write access for this feature :) 

details here - https://github.com/ZenHubIO/API#move-issue-between-pipelines

@peterjwest - this includes moving within the pipeline 🎆

**Comment by peterjwest** [comment]
Awesome! You all rock :D

**Comment by JamesToohey** [comment]
Hi guys, I get this response when posting to this endpoint:

```
{"message":"Invalid Field for pipelineId: undefined"}
```

The docs say `pipeline_id` but I've tried both, any ideas? I'm posting the name of our pipelines as a string e.g.:

```
{"position": "top", "pipelineId": "Review/QA"}
```

**Comment by JamesToohey** [comment]
@peterjwest Did you ever get this endpoint working?

**Comment by peterjwest** [comment]
I haven't had a chance yet, will probably get to it this weekend

**Comment by olegzd** [comment]
@JamesToohey Is your request body JSON encoded? If not, can you give it a shot and see if it resolves the problem?

**Comment by wulfgar61** [comment]
Is this available with enterprise yet?

**Comment by azenMatt** [comment]
@wulfgar61 - it is in the 2.14 enterprise release - https://www.zenhub.com/enterprise/releases/2-14

**Comment by JamesToohey** [comment]
@olegzd thanks for that, it now seems to work with `pipeline_id` now but I'm getting 

```
 {"message":"Invalid Field for pipelineId: In Progress"}
```

We definitely have a pipeline with that name, should we not be using the string name? I can't find an ID for the pipelines.

Thanks for your help, much appreciated

**Comment by olegzd** [comment]
@JamesToohey happy that worked.

For the `pipeline_id`, you need to provide the pipeline identifier rather than the pipeline name. This can be done using the `Get the ZenHub Board data for a repository` (https://github.com/ZenHubIO/API#get-the-zenhub-board-data-for-a-repository)

Here's a sample response from the route
```
{
  "pipelines": [
    {
      "name": "Inbox",
      "issues": [
        {
          "issue_number": 1094,
          "is_epic": false
        },

        ...

        {
          "issue_number": 1107,
          "is_epic": false
        }
      ],
      "id": "5268500c846858de1c00011b"
    }, 
    ...
```

After this, you'd take the `id` value and use it as the pipeline_id.

**Comment by JamesToohey** [comment]
Thanks @olegzd I was sure I hit that endpoint and looked for an id but I must have missed it, my apologies

**Comment by JamesToohey** [comment]
@olegzd I have it working now, thanks so much.

You may want to update the error message so show `pipeline_id` instead of `pipelineId` - that threw me off

**Comment by olegzd** [comment]
Hi @JamesToohey, glad to hear it's working on your end.

Thank you for your feedback - I just submitted a PR internally to update the error message 🙂
