### ISSUE TITLE
Zenhub API for Board with assignee

### ISSUE THREAD

**Issue by ambynair** [ZenHubIO/API#45]
@ambynair commented on [Tue Mar 21 2017](https://github.com/ZenHubIO/support/issues/1069)

I could use curl and get JSON for zenhub board a specific repository.
How do I get the same with multiple repository and for a specific assignee 

Something like this ?

curl -H 'X-Authentication-Token: 'xxxxxx' https://xxxx.xxx.com/p1/repositories/repid1+repid2/board/user/assignees

This works for single repository 
curl -H 'X-Authentication-Token: 'xxxxxx' https://xxxx.xxx.com/p1/repositories/repid1/board

**Comment by pnavarrc** [comment]
Hi, Pablo from the ZenHub team here.

Currently, the Board endpoint is specific for a repo, so in order to get the full Board data you will need to make one request per connected repo.

There are two options to get the Board data for specific assignees:

1. Fetch the Board data for each repo and use the GitHub API to fetch the assignee’s data for each issue in the Board.
2. Fetch the issues assigned to a particular user (this endpoint is also per repository) and then fetch the ZenHub data (current pipeline, estimate, epic status) using the ZenHub API (get issues data endpoint).

The second alternative is best if you only need to do this for one particular assignee, the first one will be more efficient if you need the same information for several assignees. 

The docs for the endpoint mentioned above:
- [ZenHub API - Get Board Data](https://github.com/ZenHubIO/API#get-the-zenhub-board-data-for-a-repository)
- [ZenHub API - Get Issue Data](https://github.com/ZenHubIO/API#get-issue-data)
- [GitHub API - Get Issues for a Repository](https://developer.github.com/v3/issues/#list-issues-for-a-repository)

I hope this helps you!

**Comment by ambynair** [comment]
ok, thanks. that was my plan b. Will go with option 2.
