### ISSUE TITLE
Cannot add issue to release report

### ISSUE THREAD

**Issue by veered** [ZenHubIO/API#99]
I am trying to use the API to add an issue to a release report, but it always fails with the following error: 
```Invalid request , invalid issue in add_issues```

I haven't had any problems with the other API endpoints. My code looks like this:
```ruby
require 'unirest'

endpoint = "https://api.zenhub.io/p1/reports/release/#{release_id}/issues?access_token=#{api_token}"
Unirest.patch(endpoint,
  parameters: {
    add_issues: [{ repo_id: repo_id, issue_number: issue_number }],
    remove_issues: []
  }
)
```

I've checked and the `release_id`, `api_token`, `repo_id`, and `issue_number` are all correct. Even if `add_issues` is set to be `[]` it still fails with the same error message.

**Comment by veered** [comment]
@kendramoroz Any update on this? It's blocking a pretty important update to our system

**Comment by nbcraft** [comment]
Hi @veered,

The only way I was able to reproduce your issue was to omit the header:
`'Content-Type: application/json'`

Could you make sure you are sending that header along with your request ?

If that doesn't fix it, could you provide us an example of a curl request (minus your token) that could help us reproduce the issue ?

Thank in advance.
Nathan @ZenhubHQ

**Comment by nbcraft** [comment]
Closing for now. Don't hesitate to open again if this didn't fix your issue.
